version: '3'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: "gentilis-db"
      MYSQL_PASSWORD: "fiap20202019" 
      MYSQL_ROOT_PASSWORD: "fiap20202019"
      MYSQL_DATABASE: "fiap-netflix"
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/Fernando/Documents/Projetos/workspace/mysql-data:/var/lib/mysql
      - C:/Users/Fernando/Documents/Projetos/workspace/mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 50000:50000
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
